package query

// JoinKind enumerates supported JOIN types.
type JoinKind string

const (
	JoinInner JoinKind = "INNER JOIN"
	JoinLeft  JoinKind = "LEFT JOIN"
	JoinRight JoinKind = "RIGHT JOIN"
	JoinFull  JoinKind = "FULL JOIN"
	JoinCross JoinKind = "CROSS JOIN"
)

// Join describes a single join clause. Alias is auto-generated by the
// compiler when empty, guaranteeing uniqueness for self-joins and repeated
// joins to the same table.
type Join struct {
	Kind      JoinKind
	Table     string
	Alias     string
	Condition Expr // nil for CROSS JOIN
}

// OrderTerm is a single ORDER BY term.
type OrderTerm struct {
	Column string
	Desc   bool
	Nulls  NullsOrder
}

type NullsOrder uint8

const (
	NullsDefault NullsOrder = iota
	NullsFirst
	NullsLast
)

// WindowSpec describes a window function's OVER(...) clause.
type WindowSpec struct {
	PartitionBy []string
	OrderBy     []OrderTerm
	Frame       string // raw frame clause, e.g. "ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW"
}

// SelectExpr is a single projected column/expression, optionally aliased,
// optionally a window function or aggregate.
type SelectExpr struct {
	Expr   string // column name or raw expression (already validated/escaped upstream)
	Alias  string
	Window *WindowSpec
}

// CTE describes a WITH clause entry, including RECURSIVE support.
type CTE struct {
	Name      string
	Columns   []string
	Recursive bool
	Query     any // *Builder[U]
}
